---
title: "05_Births"
output: html_document
---
### Assignment is Births and Holidays

```{r}
library(dplyr)
library(lubridate)
library(mosaic)
```

```{r}
# library(mosaic)
# Birthdays is in the mosaicData package
head(Birthdays)
str(Birthdays)
# always good to check to see if data looks reasonable
# note that date is in POSIXct format
```
```{r}
with(Birthdays,min(date))
with(Birthdays,max(date))
# see span of dates
```

```{r}
# Create a data table that adds up all the births for each day across all the states
DailyBirths <- 
  Birthdays %>%
  group_by(date) %>%
  summarise(CountUp = sum(births))
# note: do not want state in group_by. Not interested in births by state, looking at births by date
```

```{r}
# check that same years are covered
with(DailyBirths,min(date))
with(DailyBirths,max(date))
```

```{r}
# Plot out daily births vs date
DailyBirths %>% 
  ggplot(aes(x = date, y = CountUp)) +
  geom_point()
```

```{r}
# examine seasonality in birth rates
# look at number of births aggregated over all the years by:
# week, month, Julian day

# Week
PerWeek <-
  Birthdays %>% 
  group_by(weeks = week(date)) %>% 
  summarise(perweek = sum(births))
```

```{r}
# plot PerWeek
PerWeek %>% 
  ggplot(aes(x = weeks, y = perweek)) +
  geom_line()
```

```{r}
# Month
PerMonth <- 
  Birthdays %>% 
  group_by(month = month(date)) %>% 
  summarise(permonth = sum(births))
```

```{r}
# plot PerMonth
PerMonth %>% 
  ggplot(aes(x = month, y = permonth)) +
  geom_line()
```

```{r}
# Julian day
PerJulian <- 
  Birthdays %>% 
  group_by(wordday = yday(date)) %>% 
  summarise(perjulian = sum(births))
```

```{r}
# plot PerJulian
PerJulian %>% 
  ggplot(aes(x = wordday, y = perjulian)) +
  geom_line()
```

```{r}
# look at number of births by day of week
PerDay <- 
  Birthdays %>% 
  group_by(weekday = wday(date, label = TRUE)) %>% 
  summarise(letterday = sum(births))
```

```{r}
# plot PerDay
PerDay %>% 
  ggplot(aes(x = weekday, y = letterday)) +
  geom_point()
```

```{r}
DKEx1 <- 
  Birthdays %>% 
  group_by(annoyed = yday(date)) %>% 
  summarise(typical = mean(births))
```

```{r}
# plot DKEx1
DKEx1 %>% 
  ggplot(aes(x = annoyed, y = typical)) +
  geom_line()
```

```{r}
DKEx2 <- 
  Birthdays %>% 
  mutate(month = month(date), day = mday(date)) %>% 
  mutate(day = month*31 + day) %>% 
  group_by(day) %>% 
  summarise(typical = mean(births))
```

```{r}
# Pick a two-year span in the 1980s
# Extract out the data just in this interval, call MyTwoYears
# I am picking out 1980-1981 for reasons
MyTwoYears <- 
  Birthdays %>% 
  filter(year(date) == 1980 | year(date) == 1981)
```

```{r}
# plot out the births in MyTwoYears day by day
MyTwoYearsBirths <- 
  MyTwoYears %>% 
  group_by(date) %>% 
  summarise(daySum = sum(births))
```

```{r}
# now let's actually plot
MyTwoYearsBirths %>% 
  ggplot(aes(x = date, y = daySum)) +
  geom_point()
```

```{r}
MyTwoYearsBirths2 <- 
  MyTwoYearsBirths %>% 
  group_by(wordDay = wday(date, label = TRUE))
```

```{r}
# more plotting
MyTwoYearsBirths2 %>% 
  ggplot(aes(x = date, y = daySum, color = wordDay)) +
  geom_point()
```

```{r}
# read in Holiday data
Holidays <- 
  read.csv("http://tiny.cc/dcf/US-Holidays.csv") %>% 
  mutate(date = as.POSIXct(lubridate::dmy(date)))
```

```{r}
# only need 1980 and 1981 from Holidays
MyTwoHolidays <- 
  Holidays %>% 
  filter(year == 1980 | year == 1981)
```

```{r}
# draw a vertical bar at each date which is a holiday
MyTwoYearsBirths2 %>% 
  ggplot(aes(x = date, y = daySum, color = wordDay)) +
  geom_point() +
  geom_vline(data = MyTwoHolidays,aes(xintercept = date))
```
#####################################################################
#####################################################################
#####################################################################
#####################################################################
#####################################################################
```{r}
# Doing together as a class

```















